spring:
  application:
    name: niceflix

  datasource:
    url: jdbc:postgresql://localhost:5432/niceflix
    username: postgres
    password: 127799
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

flyway:
  enabled: true